### ISSUE TITLE
Seting profile photo ends up with a lack of memory

### ISSUE THREAD

**Issue by HellFinger-s** [tdlib/td#1691]
I have got a task: download user photo and set it as my profile photo(now talking about static photo)
I am downloading file: [code](https://pastebin.com/A84JmY5w)
There are no problems with that. But when I handling downloaded photo and trying to set it like my profile photo I am getting lack of memory(Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
[code](https://pastebin.com/QEvHM9vw)
Why it is happening?

**Comment by levlam** [comment]
See TDLib's log for details.

**Comment by HellFinger-s** [comment]
I should use 5th verbosity level?

**Comment by HellFinger-s** [comment]
Found some repeated errors: `[ 4][t 4][1633026327.746763944][FileDb.h:74][#1][!Td]	GET [photos, DcId{2}, [file_reference:AGFWARcPoS5CPj7b4zYkKhntQf/6], location = [ID = 5362020142684419771, access_hash = -6386059003854820961, PhotoSizeSourceThumbnail[photos, type = 97]]] [Error : 0 : There is no such a key in database] `
What could it mean?

**Comment by levlam** [comment]
Those aren't errors. The first number is log level and 4 is DEBUG.

**Comment by HellFinger-s** [comment]
Well, then I can't figure out why this is happening yet. Maybe there are some common reasons?

**Comment by levlam** [comment]
Search for a line beginning with "[ 0]".

**Comment by HellFinger-s** [comment]
Found it
`[ 0][t 4][1633095216.512038707][FileLocation.h:485][#1][!ContactsManager][&is_common()]	/home/hellfingers/.local/share/Trash/files/phptdlib/build/phptdlib/modules/td/td/telegram/ContactsManager.cpp 15731`
How I could fix it?

**Comment by levlam** [comment]
Send the whole log to @tdlib_bot in Telegram.

**Comment by HellFinger-s** [comment]
Done

**Comment by levlam** [comment]
Thanks. Fixed in master.

**Comment by HellFinger-s** [comment]
I'm sorry, but the error still persists

**Comment by levlam** [comment]
Did you update the TDLib to the latest mater version and rebuilt it?

**Comment by HellFinger-s** [comment]
Forgot, i'll do this

**Comment by HellFinger-s** [comment]
I reinstalled php extension which work with tdlib, but the error persists

**Comment by levlam** [comment]
What is returned by `getOption("version")`?

**Comment by HellFinger-s** [comment]
1.7.8

**Comment by levlam** [comment]
Does line number changed in the fatal error message? It was 15731 previously and now the code is very different on this line.

**Comment by HellFinger-s** [comment]
No, it`s at 15776

**Comment by levlam** [comment]
Could you send again TDLib's log to @tdlib_bot?

**Comment by levlam** [comment]
The sent log was from the old version. Could you check again with the latest TDLib 1.7.9 and send new log if it still crashes?

**Comment by HellFinger-s** [comment]
I`m sorry for delay. Repository author updated it 3 days ago to new version. I tryied to set profile photo and now it`s working. Thank you very much
